/*
 * changelog.js
 * "What's New" screen — a running list of user-facing additions so users can see
 * what's changed. To add a release, unshift a new entry onto CHANGELOG (newest
 * first); each item is a { title, desc } feature line.
 *
 * THIS IS THE CHANGELOG THAT SHIPS. tools/CHANGELOG.md is a leftover from the
 * upstream project — it stopped in 2022 and its links still point at that repo.
 * Add entries here.
 *
 * Write for the person using the app, not the person who wrote the patch: what
 * they can now do, and why it helps. Internal refactors and bug fixes nobody
 * noticed do not belong here; a bug they DID notice ("the radar no longer
 * disappears while you drag") does.
 *
 * This file lives under app/, so it only reaches anyone after `npm run build`
 * — which also rewrites tools/size.txt, the cache-buster the page uses. Editing
 * it without rebuilding changes nothing for users.
 */

const display_vortex_dialog = require('../menu/vortex_dialog');

const CHANGELOG = [
    {
        date: 'October 1, 2026',
        items: [
            { title: 'Warning notifications on your phone', desc: 'You can now be notified when a warning is issued for a place you care about, with the app closed. Open Alert Notifications in the menu, turn them on, and add the places you want watched by address, city or ZIP. A notification is sent only when the place is inside the warning polygon the forecast office actually drew — not merely in the same county — so it fires when it matters and stays quiet when it does not. There is a Test button, because the time to find out notifications are not reaching your phone is not during a tornado warning. Quiet hours are respected, except by the alerts that can kill you: a tornado warning will always come through. Nothing is sent for warnings that were already active when you turned it on, and a repeated or updated warning does not notify twice.' },
            { title: 'The brand watermark takes video', desc: 'The logo overlay accepts an MP4 or WebM as well as a still, so you can put an animated bug on the radar for a stream. It loops silently in the corner you choose, with the same size and opacity controls, and is saved to your account like a logo. One difference worth knowing: a still image is shrunk for you before it is stored, and a video cannot be, so it is kept exactly as you gave it — the limit is 8 MB, and you are told the size of anything larger rather than finding out when it fails to save.' },
            { title: 'Hurricane models, for whatever storms are running', desc: 'HWRF and HMON are in the model list, and they follow the storms on their own. Both are run once per tropical cyclone rather than over a fixed area, so the panel asks which storms are being modelled right now and offers them — a storm that forms tonight appears by itself and one that dissipates stops being listed, with nothing to set up. Pick a storm and you get its forecast out to five days in three-hour steps, framed on its basin. The new RRFS is in the list as well, at 3 km over the country with 84-hour runs four times a day. Nothing was removed to make room: both NAM entries are exactly where they were.' },
            { title: 'Choose your satellite view: GeoColor or infrared', desc: 'The satellite layer now offers two pictures, picked on its legend. GeoColor is the one that looks like a photograph of the planet — true colour by day, and at night an infrared blend with city lights showing. Infrared is the working view: its colours are cloud top temperatures, so the coldest, tallest parts of a storm stand out, and it works the same at three in the morning as at noon. Your choice is remembered. The legend changes with it, since the temperature scale belongs to the infrared and GeoColor has no scale to read along. Both satellites are used now rather than just the eastern one, so the picture runs from the middle of the Pacific to well out into the Atlantic instead of stopping at the coasts. On the 24/7 channel the same choice is available too.' },
            { title: 'Satellite: you could see through the middle of a storm', desc: 'The coldest part of a deep storm was being drawn transparent, so you could see the map through the centre of a hurricane. The colour scale draws the very coldest tops, between about -70 and -79, as shades of grey, and those shades sit one or two steps away from the greys that mean warm ground — which are meant to be invisible so the map shows through. The lookup was rounding colours off before reading them, which put the two within one step of each other, and the warm reading won. Greys are now read at full precision, so the inside of a storm is drawn solid while clear ground stays transparent. Also fixed: an occasional white flash in the satellite loop. The imagery service sometimes serves a blank white frame, and white is the coldest reading on the scale, so it was being drawn as the highest cloud top on earth across the whole picture. A frame dominated by one colour is now recognised as blank and skipped — measured against real imagery, where the commonest colour covers under one percent of the picture, against a hundred percent for a blank.' },
            { title: 'The 24/7 channel covers the tropics', desc: 'With a tropical system in the Gulf, the channel switches to covering it: looping infrared satellite over the Gulf, the Caribbean and the western Atlantic, with the National Hurricane Center forecast tracks drawn on top and the storm categories colour-coded. Radar is off while this runs, and so are the radar site markers, because a tropical system spends most of its life over water where no radar can see it — the national mosaic would show an empty Gulf and there would be nothing for the single-site view to cut to. The counters and the strip along the bottom now list the tropical products rather than the thunderstorm ones — hurricane and tropical storm watches and warnings, and storm surge, in the colours the National Hurricane Center uses, since on a day like this there are rarely any tornado or hail warnings to list. Both satellites are used, east and west, so the picture fills the screen instead of stopping partway across it. The satellite loops through the last hour and the picture names itself as satellite rather than radar throughout.' },
            { title: 'The satellite loops', desc: 'Satellite plays now instead of standing still: the last hour of scans, six frames ten minutes apart. It runs on the player at the bottom of the screen along with everything else — press play and the satellite plays, drag the slider and it moves with you — rather than animating to a clock of its own beside it. It follows by time rather than by frame number, so the satellite picture you see is the one taken closest to the radar frame on screen; the two hold scans at different rates, and matching them by position would have paired pictures taken half an hour apart. The time of the satellite frame is on its legend with its age, so you can always see which moment you are looking at. With no radar loaded the player drives the satellite itself — play, the slider and Live all work on it, because the controls now take whichever layer is actually loaded rather than radar alone. It also finds the newest scan rather than assuming one — the feed usually runs about half an hour behind, and by how much varies — so the loop never opens on a blank frame.' },
            { title: 'Satellite now shows how cold a storm is', desc: 'The satellite layer was washing storms out, and the colder the cloud top the worse it got — which is exactly backwards, because cold tops are the tall, dangerous ones. NASA sends this imagery already coloured: grey for low cloud, then cyan, green, yellow, orange, red, magenta and white as tops get higher. The layer was deciding what to hide from how BRIGHT each pixel looked, and the colours marking the coldest tops are dark ones, so the heart of every deep storm was being faded out or deleted while the harmless cloud around it stayed. It now works out the actual temperature of each pixel from its colour and hides cloud by how warm it is instead. Deep convection is drawn solid, overshooting tops with it, and clear ground and sea are left almost fully transparent so the map underneath still reads. The imagery is also drawn at the full resolution the satellite provides, rather than half of it, and there is a temperature scale on screen so you can tell a -40 anvil from a -80 top.' },
            { title: 'The 24/7 channel restarts before the browser runs out of memory', desc: 'The channel has twice ended up broadcasting a browser crash page, on two different servers. The cause is the browser slowly using more memory the longer it runs, until it gives up — and the channel reloading its own page every six hours does not help, because a reload keeps the same browser. It now watches how much memory the browser is using and restarts cleanly before it gets there, which takes a few seconds and happens at a moment of its choosing rather than at three in the morning. If one does crash anyway, the channel now notices in ninety seconds rather than three minutes.' },
            { title: 'Smoother cuts on the 24/7 channel', desc: 'Pulling back to the national map used to lurch. The channel started the move and then immediately fetched and decoded the national mosaic on top of it, which is the heaviest thing the page does — and it had taken the storm radar away first, so the camera struggled through an empty map and the weather only appeared once it landed. Nothing heavy now happens while the camera is moving. The storm you were watching stays on screen and shrinks away as the country comes into view, the national picture is drawn once the camera has settled, and the pull-back itself is a little slower so it reads as a pull-back rather than a snap. Cutting to a storm got the same treatment: the radar is drawn once, when the camera arrives, instead of once in mid-flight and again on landing, and it fades in over a fifth of a second rather than appearing all at once. The loop between frames is untouched and still instant, because fading there would smear one scan over the next.' },
            { title: 'The 24/7 channel points at a radar that can see the storm', desc: 'The channel could put a warning on screen with an empty map under it: the right site name, a scan from four minutes ago, and no weather anywhere. It was choosing the nearest radar to a warning without asking whether that radar could see it, and the nearest one is sometimes two hundred miles away, with the warned county off the edge of its picture entirely. It now only cuts to a radar within range of the storm, the same rule the quiet-weather tour has always used. The scrolling warning strip along the bottom has also been rebuilt: it used to reach the end, leave an empty bar, and visibly snap back to the start, and it ran at a speed that depended on how many warnings there were, so one warning crawled and a busy day raced past. It now runs at a steady readable pace and loops without a seam.' },
            { title: 'The 24/7 channel will not broadcast a black screen', desc: 'The channel went out black, and stayed black, while every signal there was said it was healthy: the video was arriving, and YouTube and Twitch both rated the connection excellent. All of that was true. None of it was checking that there was anything to broadcast. The browser had failed to start at all, so the channel was faithfully transmitting an empty screen. It now refuses to go on air until the browser is running and the page itself has reported in, and it keeps checking both while it runs, so a channel that loses its picture comes back on its own instead of transmitting nothing until somebody happens to look.' },
            { title: 'The 24/7 channel restarts itself if the browser crashes', desc: 'The channel could end up broadcasting a browser crash page, and keep broadcasting it, because every check it had for things going wrong ran inside the page itself and a crashed page cannot notice its own crash. The streaming side now watches from outside: the page reports in every thirty seconds, and if it stops reporting, whether from a crash, a hung tab, or the browser being shut down to save memory, the stream is restarted from scratch rather than left pointing at a dead screen. If the site itself is down it waits for the site to come back, rather than restarting over and over.' },
            { title: 'Layers menu beside the search bar', desc: 'A Layers button now sits next to the search box, holding Radar, Satellite, Models and Outlooks. Radar and Satellite switch those layers on and off and show you which are on; Models and Outlooks open their panels. The buttons drive the same controls as the menu rather than copying them, so the two can never disagree with each other, and the button travels with the search box at any window width. "Satellite" here is the GOES satellite imagery layer — the satellite base map is still under map style in the settings menu.' },
            { title: 'Side-by-side panes can show two different storms', desc: 'In split screen, clicking a radar site used to change BOTH panes, so you could never compare two different storms. Now each side keeps its own site and product. Radar sites appear on BOTH maps, so you pick a site on the map you want it on, and the controls follow to that side. Opening split screen still starts the right side on the left side\'s site, so it opens as a comparison rather than an empty map; it simply stops following after that. Switching the map itself — Echo Radar map, satellite view — still changes both sides together, so the two always look alike. With split screen off, nothing changes.' },
            { title: 'The 24/7 channel stops eating memory', desc: 'The 24/7 channel was using more and more memory the longer it ran, enough to run a small server out of it. Each frame of the radar loop is a full scan decoded in the browser, and the decoding was holding on to far more of them than it needed — so the work is now thrown away as soon as each frame has been drawn. Measured over six storms on five different radars, memory now settles back where it started instead of climbing: it grew by 83 MB across the whole run, where before it had grown by more than three gigabytes in two.' },
            { title: 'The 24/7 channel can no longer sit on an empty map', desc: 'The 24/7 channel could end up showing the map with no radar on it at all, and stay that way. A camera move that the map refused — which happens when the on-screen panels leave too little room — was throwing before the national radar had been switched back on, and nothing ever retried because the page already believed it was on the national view. The camera can no longer break the radar, the page puts the national map back if it ever finds nothing on screen, and an empty map is now something it actively watches for rather than the one state it could not see.' },
            { title: 'The 24/7 radar plays, instead of standing still', desc: 'The radar on the 24/7 channel plays now instead of standing still. The last few scans run as a loop, with the time of the frame you are looking at on the chip and a marker showing how many frames are running — so it is obvious at a glance that the picture is live and not a screenshot, and so you can see which way a storm is actually moving. The loop builds behind the still frame, starts as soon as it has two scans, and follows the stream from storm to storm.' },
            { title: 'The 24/7 channel cannot freeze any more', desc: 'The 24/7 channel could get stuck showing one picture indefinitely. If anything went wrong in the moment it was switching to a new storm — a bad warning outline was enough — it stopped choosing what to show, while the clock kept ticking and the radar kept refreshing, so it looked perfectly alive. That cannot happen now, and as a backstop the page restarts itself if it ever goes ten minutes without making a decision. It also stops trusting the warning list if the National Weather Service feed goes quiet for a quarter of an hour, rather than leaving an expired warning on screen it can no longer check.' },
            { title: 'A steadier 24/7 channel that moves on', desc: 'Two fixes to the 24/7 channel. It was holding one warning on screen for hours: a warning alone in its class had nobody to hand over to, which is exactly what happens when one flash flood emergency is the most serious thing in the country. Anything on air now gives the rest of the weather a turn eventually — a tornado or a declared emergency keeps it four times longer than ordinary weather, but no longer keeps it indefinitely. And the picture no longer freezes: decoding a newly arrived radar scan was locking the page up for two and a half seconds at a time, and now happens out of the way in the background. The worst pause is under a third of a second.' },
            { title: 'The 24/7 channel shares the air again', desc: 'The 24/7 channel was parking on one warning and staying there. It takes turns between storms of the same kind again — it had quietly stopped doing so once the ranking learned to tell two severe storms apart by hail size, which gave every warning a score of its own and left the leader with nobody to hand over to. The biggest threat still goes on first, and anything more urgent still interrupts. The page is also much lighter to watch in a browser window: the map was being drawn at full broadcast size and then shrunk by the browser on every frame, so a smaller window cost more work than a big one.' },
            { title: 'Flash floods, watches, and a steadier picture', desc: 'The channel now breaks to flash flood warnings and flood warnings as well as tornado and severe thunderstorm ones, names a flash flood emergency when an office declares one, and shows watches when nothing is warned — so there is live radar on screen whenever there is weather, not just during severe storms. Watches are drawn dashed, counted separately, and never outrank a warning. The national map is now the fallback rather than a regular turn: if there are storms anywhere, you get a radar site looking at them instead. The picture also stops hitching — the radar image was being built in a way that froze the page for a third of a second every time it refreshed, and the warning ticker restarted its scroll every minute whether anything had changed or not.' },
            { title: 'Radar sites and app radar on the 24/7 channel', desc: 'The broadcast channel now carries the same radar site markers as the app — blue for a working radar, amber for a TDWR, red for one that has stopped reporting — from the same list and the same live status the app uses. And it no longer needs a warning to show you a real radar: when there are storms but nothing is warned, it finds the strongest cells in the country and tours them on the nearest site, at the same super-res detail the app draws. The national map stays in the rotation so you still get the wide picture between storms, and any warning interrupts all of it.' },
            { title: 'The 24/7 channel breaks to the storm', desc: 'When a tornado or severe thunderstorm warning is active, the broadcast view no longer sits on the national map. It picks the most urgent warning, finds the nearest radar site, and puts that radar on air — base reflectivity at full super-res detail, zoomed to the warned area, with the storm details beside it: hail size, wind gust, which way it is moving and how fast, whether a tornado is radar indicated or confirmed, who issued the warning, and how long is left on it. When the warning ends it goes back to the national map. A more urgent warning interrupts, and during an outbreak it shares the air between storms rather than staying on one county all afternoon. It never says more than the National Weather Service said — a tornado is called confirmed only when the office says it was observed.' },
            { title: 'A 24/7 national radar channel', desc: 'There is now a broadcast view at /broadcast — national MRMS composite reflectivity, with live warnings drawn as outlined boxes over the radar — red for a tornado warning, yellow for severe thunderstorm, green for flash flood, each labelled and outlined dark so it reads over bright echo — plus counters, a warning ticker and the radar\'s own age on screen. It is built to run unattended and stream to YouTube around the clock from the server, so nobody has to leave a computer on.' },
            { title: 'Model fields cover the whole model', desc: 'A field from Models & Forecast — temperature, CAPE, precipitable water — was drawn only for the piece of map you happened to be looking at when you pressed it, and pinned there. Zoom out or pan and you were left with a coloured rectangle over one corner of the country. Each field now covers the model\'s entire area: the whole CONUS grid for HRRR, NAM and NDFD, and the whole world for GFS, GEFS and ECMWF. Pan and zoom freely — the field stays under you.' },
            { title: 'Graphics templates are framed properly', desc: 'The map in the Studio templates ran right to the edges of the frame, so a state or a county group sat under the title and legend bars and left no room to read it. Every template now pulls back from the edges, with the surrounding area visible for context. The brand block on the radar and model templates also still said Vortex; it says Echo now.' },
        ],
    },
    {
        date: 'September 29, 2026',
        items: [
            { title: 'Radio: you can be heard again', desc: 'On the PTT radio, audio often only travelled one way — you could hear someone but they could not hear you, and refreshing the page just swapped who was deaf. Whichever side answered the call was connecting its microphone to the wrong end of the line, so the connection looked perfectly healthy while your voice went nowhere. Both directions now work, including after a refresh.' },
            { title: 'Global PTT listening removed', desc: 'The Global PTT live listening feed has been taken out of the app. The PTT radio — channels, hold to talk — is unaffected.' },
            { title: 'A tidier map, and a new way into the menu', desc: 'The alert counter has moved to the top right, and the Echo Radar mark now sits in the top left corner — tap it to open layers and settings. That clears two icons off the bottom bar: the settings sliders, which the mark replaces, and the Global PTT headphones, which no longer does anything.' },
            { title: 'Soundings no longer get cut off', desc: 'When the sounding fell back to the built-in plot, the note explaining why was placed beside the chart instead of beneath it, so both were clipped at the edges of the window — the model name lost its first letter and the note lost its right-hand side. They stack properly now.' },
            { title: 'Sponsors', desc: 'The sponsors page is now simply an invitation: if you would like to sponsor Echo Radar, email admin@extremeweathervideos.com.' },
        ],
    },
    {
        date: 'September 25, 2026',
        items: [
            { title: 'Vortex Radar is now Echo Radar', desc: 'Same app, same team, new name and a new look. You may need to refresh once for the new name and icon to appear, and if you added the app to your home screen you may want to remove and re-add it to pick up the new icon. Nothing about your account, your saved locations or your subscription changes.' },
            { title: 'Our Team is up to date', desc: 'The team list under Our Team now shows the current roster, with where each person is based, and the app is credited to EWV extremeweathervideos LLC.' },
        ],
    },
    {
        date: 'September 11, 2026',
        items: [
            { title: 'Highway shields on the map', desc: 'Interstate, US highway and state route shields now show on the radar map, drawn on top of the radar, so you can tell at a glance which road a storm is crossing and where you are. Interstates appear from far out; US highways, then state routes, fill in as you zoom closer. They are on for everyone; if you would rather not see them, switch off Highway Shields in the settings menu, and the app remembers your choice.' },
            { title: 'Live button', desc: 'Beside the loop controls there is now a LIVE button. Its red dot is lit while the map is showing the newest scan and updating itself. Play a loop, step through it or drag the timeline and it dims; press it (or the L key) to stop the loop, jump to the newest scan and pick up any that arrived while you were looking back. Before this, pausing a loop left the map sitting on an old scan with nothing updating it. A new scan arriving in the middle of a loop is also no longer drawn over the top of it.' },
            { title: 'Storm tracks no longer flash', desc: 'Storm tracks and tornado markers blinked every time the radar updated, and several times a second while a loop played. Every radar refresh was deleting them and drawing them again from scratch, because the check meant to skip a file it had already drawn never actually remembered what it had drawn. They now stay put, and only change when a new storm-track file arrives — and even then they update in place rather than vanishing first. Clicking a storm also opens a single popup again, where a long session could stack up several identical ones.' },
            { title: 'Tornado vortex signature markers now appear', desc: 'The tornado symbols for radar-detected vortex signatures were not showing on the map at all: the markers asked for an icon by a different name from the one it was loaded under, so there was nothing to draw. They now appear, and update alongside the storm tracks.' },
            { title: 'Radar loops up to 75 frames', desc: 'Next to the speed control there is now a choice of loop length: 10, 25, 50 or 75 scans. Seventy-five is five to seven hours of radar, enough to watch a line form and cross a whole region. Loops also load far faster than before — they used to fetch one scan at a time and look each one up separately, and now they look them up once and download several at a time, with a counter showing how far along it is. A loop that reaches back past midnight UTC no longer skips scans at the change of day, and one scan that fails to download costs that one frame instead of freezing the whole load. It starts at 75 on every device, phones included — pick fewer on mobile data, since a 75-frame loop is about 21 MB.' },
        ],
    },
    {
        date: 'September 9, 2026',
        items: [
            { title: 'The Graphics Studio now looks like a graphics application', desc: 'The Studio has been rebuilt around the way broadcast graphics software actually works. There is a menu bar and a ribbon of tools across the top, and the workspace is divided into named panels you can collapse or close: your Project list on the left, the Preview in the middle on a transparency checkerboard, a Program Monitor on the right, and the properties for whatever you are editing along the bottom. Your templates all appear in the project list with a thumbnail of what each one currently produces, so you pick a graphic by looking at it rather than by reading names. And there is now a proper Take: the Preview is what you are building, the Program Monitor is what you have sent out, and editing after a take no longer changes what you already put on air.' },
        ],
    },
    {
        date: 'September 8, 2026',
        items: [
            { title: 'The professional radar reads like a radar console', desc: 'The licensed interface now carries the instruments an analyst expects. Products sit across the top as the codes they are known by — BR, BV, SRV, CC, ZDR, KDP, HCA, VIL — and one click switches to them, with the loaded one filled in so you can see at a glance what you are looking at. The colour scale stands on its end against the left edge of the image, where you can read a value off it in the same glance as the storm. The site, VCP, product and elevation are written into the corners of the image itself, so you never have to look away from the weather to check which tilt you are on. Range rings mark 50, 100, 150 and 200 nautical miles from the antenna. And the status bar answers the question a radar operator actually asks: the azimuth and range of whatever is under the cursor, the height of the beam at that range, the exact latitude and longitude, and the scale of the image in metres per pixel.' },
            { title: 'A professional interface for licensed operators', desc: 'Accounts with an Echo Pro licence now get a different radar interface: a docked workstation in the style of the desktop analysis tools, rather than rounded controls floating over the map. A tool dock down the left lists every tool by name instead of as an unlabelled icon, the site, product, elevation and VCP sit in a readout strip across the top, and a status bar along the bottom carries the playback controls, the frame counter, the scan time and a live cursor position. It is the same radar underneath — the same controls, moved. Everyone without a licence keeps the interface they already have, unchanged.' },
            { title: 'Echo Pro — a workspace built for newsrooms', desc: 'A new professional edition at /pro, for television and radio stations, school districts and emergency management agencies. It is a different screen from the radar, not a reskin of it: you set the counties your operation covers, and warnings for those counties are promoted to the top of the board with the population affected, how long each has left, and whether a tornado warning is radar indicated or confirmed on the ground. It writes your on-air crawl copy for you, groups warnings the way you would read them out, and puts a full-screen banner up the moment a tornado warning is issued inside your coverage area. An On Air button strips the interface away to a clean full-bleed map for a camera shot. Access is granted per organisation by an administrator — it is not something a consumer account can buy into.' },
            { title: 'Crawl times now read in the warning\'s own time zone', desc: 'Expiry times are written in the time zone of the office that issued the warning, taken from the warning itself, rather than in whatever zone the computer happens to be set to. A producer covering a market from out of state was previously being shown a time that was an hour or more wrong, with a confident time zone label attached to it, in the box designed to be copied straight onto air.' },
        ],
    },
    {
        date: 'August 31, 2026',
        items: [
            { title: 'PTT audio finally reaches the speaker', desc: 'The connection was coming up healthy while no sound could arrive. The incoming voice was being handed over without the wrapper the player expects, so it was dropped on the floor. The radio now takes the audio directly off the connection once it is up, rechecks every few seconds, and repairs itself instead of staying silent until you rejoin.' },
            { title: 'PTT connections were failing before they started', desc: 'The radio showed everyone as connected while no audio could ever flow. The messages that let two people find a route to each other were being thrown away when they arrived a moment early — which is most of the time — so the connection had nothing to work with and quietly stalled. They are now held and used as soon as they can be. The panel also shows the real connection state, and says plainly when two networks cannot reach each other directly.' },
            { title: 'PTT: you can hear each other now', desc: 'Incoming radio audio was being silently blocked. The browser refuses to start audio before you have clicked anything, and the code noted the refusal and never tried again — so if someone started talking before you touched the app, they stayed inaudible for the whole session. Audio is now retried the moment you interact, and the panel says so if it is waiting. With nobody able to hear anyone, it looked like the microphone was broken too; it was not.' },
            { title: 'Playback no longer crashes phones', desc: 'Pressing play could lock the app up and take the phone with it. Three causes: it queued the next frame on a fixed timer whether or not the last one had finished drawing, so on a slow device the frames piled up until nothing responded; it held ten full scans in memory at once, which a phone does not have; and tapping play while it was still loading did nothing, with no way to stop it. It now waits for each frame before scheduling the next, keeps five scans on a phone, and a second tap cancels a load that is under way.' },
            { title: 'Graphics Studio and 3D Storm View are desktop-only', desc: 'Both were reachable on phones, where they exhaust memory and crash the app — the Studio decodes super-res radar in the browser and the 3D view renders a whole sweep in WebGL. They are now hidden on phones and tablets instead of being offered and failing.' },
            { title: 'National Radar: sharper, and no more flicker on zoom', desc: 'Two fixes. It now draws at your screen’s resolution and blends the data before choosing colours, so colour edges land crisply instead of being stretched and smeared — that was the real cause of the blur. And zooming no longer rebuilds the whole layer each time: the picture is updated in place and encoded off the main thread, so the flashing and stutter are gone.' },
            { title: 'National Radar is sharp when you zoom in', desc: 'It drew one picture of the whole country and stretched it to fit, so zooming into a county meant magnifying that picture about fifteen times — soft blobs however good the data was. It now draws just the part you are looking at, at the full 1 km detail the mosaic actually has, and redraws as you pan. Zoomed out to the whole country it looks exactly as it did.' },
            { title: 'National Radar uses your colortable', desc: 'The national radar coloured reflectivity from its own built-in table, so it never matched the single-site radar and an uploaded colortable changed one but not the other. It now reads the app’s own table — the same one the single-site radar uses — and repaints the moment you pick a different one.' },
            { title: 'National Radar honours smoothing', desc: 'The Smoothing setting governed the single-site radar but not the national mosaic, which stayed visibly blockier beside it. It now follows the setting: on, each pixel averages the area it covers instead of grabbing one cell, which removes the stair-stepping without softening storm cores; off, you get crisp cells.' },
            { title: 'National Radar was drawn ~150 miles too far north', desc: 'This is the big one. The MRMS mosaic was being stretched onto the map using the wrong projection, which slid every echo northward — by up to 150 miles through the middle latitudes. Storms off the Carolina coast were painted over Washington DC; rain in south Georgia showed over central Georgia. The data was always right; where it was drawn was not. Fixed, and now accurate to under a mile. Model overlays had the same fault, up to 80 miles on a nationwide view, and are fixed too.' },
            { title: 'National Radar', desc: 'The MRMS layer is now labelled for what it is — National Radar: one seamless observed picture of the whole country, built by NOAA from every WSR-88D, updating about every two minutes. Not a model and not a forecast. Its legend shows the frame time so you can always see how current it is.' },
            { title: 'You can see what a layer is showing you', desc: 'MRMS now carries a legend with the product, its colour scale, the frame’s time and how old it is — and says STALE outright if the feed stops. Model overlays say FORECAST with the model and valid time. A model composite reflectivity and a live national mosaic cover the same ground and look alike; nothing on screen used to tell you which one you were looking at.' },
            { title: 'MRMS is now 25 products, not one', desc: 'The MRMS layer showed a single field — base reflectivity — with no way to change it. It now has a product picker covering the national grids worth watching: four reflectivity fields, AzShear and rotation tracks for spotting couplets, MESH and POSH for hail, echo tops, VIL, VIL density and VII, precipitation rate and type, and radar-only and multi-sensor QPE out to 24 hours. Each has its own colour scale and units; reflectivity still uses your own colour table so it matches the single-site radar.' },
            { title: 'Dropdowns are readable', desc: 'Opening a dropdown showed a white sheet with near-white text on it — the list a select opens is drawn by the operating system, and it was ignoring the app’s dark theme. Every dropdown in the app now opens dark and legible, not just the ones on the sounding.' },
            { title: 'Forecast hours match the model', desc: 'The sounding offered the same lead times whatever model you picked, so half of them failed on the short-range ones. Each model now lists only hours it actually runs — hourly detail for the HRRR and NAM 3 km nest, out to 10 days on the GFS — and switching models keeps the hour you were on when the new one has it.' },
            { title: 'Real SHARPpy soundings', desc: 'The forecast sounding now renders the full SounderPy/SHARPpy analysis — the same plot the reference sites publish. Parcel traces for surface, mixed-layer and most-unstable parcels, the Bunkers hodograph with storm-motion vectors, the complete CAPE/CIN/LCL/shear/SRH tables, streamwiseness and storm-relative wind panels. Available on all five models.' },
            { title: 'Soundings on every model', desc: 'The forecast sounding was GFS-only. HRRR, NAM, the NAM 3 km nest and ECMWF are now all available from the model dropdown, out to the same lead times.' },
            { title: 'NAM winds were wrong — fixed', desc: 'Anywhere the NAM or NAM 3 km nest showed wind, it was reading the wrong half of the file: NOAA packs the east and north components into a single record, and both were decoding as the same one. Soundings showed impossible wind speeds. Wind, shear, storm motion and barbs on those two models are all corrected.' },
            { title: 'The sounding tells you what it is showing', desc: 'If the exact SHARPpy plot is unavailable on your server, the panel now says so underneath the built-in one — with the command to install it — instead of quietly drawing something that looks different.' },
            { title: 'Named QPF windows', desc: '3, 6, 12, 24, 48 and 120-hour precipitation totals ending at whichever forecast hour you are on. A window only appears once the run has gone far enough to compute it, so there is never a button that cannot work.' },
            { title: 'Wind barbs', desc: 'Wind at 10 m, 850, 500 and 250 mb drawn as proper barbs — pennants, full and half barbs, and an open circle for calm — so you can read direction as well as speed. A shaded map can only ever show you speed.' },
            { title: 'Anomalies', desc: 'Precipitable water and 2 m temperature as a departure from normal, against the 1981–2010 daily climatology for that forecast’s valid date. 25 mm of moisture is unremarkable on the Gulf coast and extraordinary over Montana; this is the map that tells them apart.' },
            { title: 'Combination plots', desc: 'Shaded field with wind barbs over it in one image — SBCAPE with surface barbs, MLCAPE with 0–6 km shear barbs, the Supercell Composite with shear barbs, MSLP, theta-e and 500 mb wind. Reading instability against the wind that will organise it is the whole point, and flipping between two overlays loses it.' },
            { title: 'HRRR forecast hours are correct', desc: 'A freshly started HRRR run listed forecast hours it had not produced yet — all 24 of the day’s runs share one folder and the scan was not separating them — so picking one of those hours failed. It now offers only what the run has actually posted.' },
            { title: 'A full product menu for the models', desc: 'Models & Forecast now has the whole forecast-desk product list, grouped the way you read it: Surface, Precipitation Type, Quantitative Precipitation, Integrated Moisture, Radar, Severe Weather (Instability, Wind Shear, Composite Parameters), Upper-Air Moisture and Dynamics, and Winter Weather. The HRRR carries 51 of them. Each model only shows what it actually has — no card that fails when you click it.' },
            { title: 'Computed severe parameters', desc: 'Fields that are not in the model file are now worked out from the ones that are: 0–6 km, 0–1 km and surface-to-500 mb bulk shear, 700–500 and 850–500 mb lapse rates, LCL and LFC height above ground, 2 m theta-e, EHI, the Supercell Composite, and precipitation type from the rain/snow/sleet/freezing-rain flags. Precipitation type gets a proper category legend rather than a colour bar.' },
            { title: 'ECMWF', desc: 'The ECMWF IFS at 0.25° joins the model list, out to 144 hours — 2 m temperature and dew point, 10 m wind and gusts, MSLP, QPF, cloud cover, precipitable water, MUCAPE, lapse rates, and upper-air winds, temperatures and humidity.' },
            { title: 'Precipitation rate actually shows up', desc: 'The Precipitation Rate field was drawing nothing at all — it is stored in units a thousand times smaller than the scale it was being coloured against, so every value fell off the bottom. It now plots in mm/hr.' },
            { title: 'NAM 3 km CONUS nest', desc: 'The NAM’s high-resolution 3 km CONUS nest joins the model list in Models & Forecast — hourly out to 60 hours, with the full severe set including MLCAPE, MUCAPE and 0–6 km shear at four times the detail of the 12 km NAM.' },
            { title: 'The NAM’s forecast hours are back', desc: 'Picking the NAM gave you a run with no forecast hours to step through. Its files share a folder with every other NAM product, and the listing was being cut off before reaching them. All 53 hours out to +84 are there again.' },
            { title: 'CAPE and shear in Models & Forecast', desc: 'Six new quick fields for severe setups: MLCAPE and MUCAPE alongside the existing surface CAPE, 0–6 km and 0–1 km bulk shear, and 0–3 km and 0–1 km storm-relative helicity. Bulk shear is computed from the model’s wind-shear components and drawn in knots, so you get the number you actually forecast off rather than two raw component fields. Each card only appears on the models that carry it — HRRR has all six, the NAM and GFS a subset.' },
            { title: 'Cameras & More is one section', desc: 'The menu’s Cameras and More groups are now a single “Cameras & More” section — Live Cameras, Live Cams, BuoyCAMs, Earthquakes, NOAA Weather Radio and Power Outages together, one heading to open instead of two.' },
            { title: 'Drawings show on both panes', desc: 'Mark up a storm in split screen and the same mark appears on the other pane, over the same ground. Draw on either side — it copies to the other. Turn split screen off and the copy goes away, leaving what you actually drew.' },
            { title: 'Split screen works like you’d expect', desc: 'Click a pane to select it, then pick from the product menu you already use — that pane changes, the other one stays put. So you can hold reflectivity on the left and flip the right through velocity, correlation coefficient and back without losing your place. The separate right-pane control box is gone; there is one set of controls now, and a highlight around the edge of a pane shows which map you are driving.' },
            { title: 'Both panes wear the Echo Radar map', desc: 'The second pane now uses the same basemap as the first, instead of opening as a stock dark Mapbox map beside it. Both panes share whichever radar site you pick on the left, so the comparison is always the same storm.' },
        ],
    },
    {
        date: 'August 28, 2026',
        items: [
            { title: 'Shift+V for velocity', desc: 'Press Shift+V to jump straight to velocity and Shift+R to go back to reflectivity, without opening the product menu. Works on WSR-88D, TDWR and Level 2 — it picks the right product for whichever radar you are on. Press ? for the full shortcut list.' },
            { title: 'Severe, Tropical and Fire settings', desc: 'The settings menu now has three dedicated screens under Tools — Severe, Tropical and Fire — instead of one SPC Outlooks page. Severe keeps the convective outlooks, Tropical gathers the NHC layers (hurricanes, spaghetti models, hurricane hunters, Atlantic and E Pacific tracks), and Fire brings the fire weather layers and SPC fire outlooks together in one place.' },
            { title: 'Live wildfire perimeters', desc: 'Two new Fire layers show what is actually burning: Fire Perimeters draws the burned area shaded by how contained it is, and Active Fires plots incidents sized by acreage. Tap either for acres, containment, cause and when it was first reported. Data from the interagency NIFC feeds, refreshed every few minutes.' },
            { title: 'Station plot shows dew point', desc: 'The METAR station layer now plots dew point rather than temperature — the field that actually tells you whether there is moisture to work with, and one that does not swing with afternoon heating. Tap a station for the full observation, temperature included.' },
            { title: 'The bottom bar folds away', desc: 'A handle on the left of the bar folds it down to nothing but that handle, so you can see the whole map on a smaller screen. It remembers whether you left it open or closed.' },
            { title: 'SPC Fire Weather outlooks', desc: 'SPC Outlooks now include Fire Weather for Day 1 and Day 2 — Dry Thunderstorms and Wind &amp; Relative Humidity — alongside the convective outlooks, drawn in SPC&rsquo;s own colours.' },
            { title: 'Panels scroll on smaller screens', desc: 'Models &amp; Forecast and the other side panels now scroll properly. On a laptop — or any short window — the lower part of a panel used to be cut off with no way to reach it, so Quick Fields ran off the bottom and “All variables” could not be opened at all. Short screens also get a little more room and tighter spacing.' },
            { title: 'EOC Mode', desc: 'A new emergency-operations board at /eoc — a different interface built for running an incident rather than watching the weather. Active warnings sorted by what matters first, a live population-affected count resolved from the actual counties each warning covers, field reports arriving as they’re filed, spotters, storm tracks, power outages, PTT and cameras, plus hospitals, schools and shelters for wherever you’ve got the map. Confirmed tornado warnings and catastrophic damage threats are called out on sight.' },
            { title: 'Live Radar in Graphics Studio', desc: 'A new Studio template with a map you can actually move — drag to pan, scroll to zoom, and compose the shot directly instead of picking a region from a list. The radar is the app’s own super-res Level 2, decoded right in your browser with the same decoder and the same colortables as the radar page, so a graphic and the live radar agree gate for gate. Pick any WSR-88D, or let it follow whichever radar you were just watching.' },
            { title: 'Radar loops in the Studio', desc: 'Press Play to loop the last several scans for the site on screen and watch storm motion without leaving the Studio. Frames are prepared before the loop starts, so it plays smoothly instead of stuttering on its first pass.' },
            { title: 'Live button', desc: 'Jump straight back to the newest scan from anywhere in a loop. It lights up whenever you’re on current data, so at a glance you can tell live radar from loop history.' },
            { title: 'Smoother panning', desc: 'Moving the map is much faster, and the radar no longer disappears while you drag it.' },
        ],
    },
    {
        date: 'July 29, 2026',
        items: [
            { title: 'Wind Particles', desc: 'A new velocity-flow overlay — animated particles stream along the radar velocity field and swirl around storm rotation, so you can read a storm’s motion at a glance. Works over any product and follows the tilt you’re viewing.' },
            { title: 'Filtered Active Alerts list', desc: 'The Active Alerts list now respects your alert filters — warning types you’ve turned off no longer show up in the list either, so you only scroll through the alerts you actually want to see.' },
        ],
    },
    {
        date: 'July 20, 2026',
        items: [
            { title: 'GOES-19 Clean IR satellite', desc: 'New satellite layer — GOES-19 (GOES-East) Clean Longwave Infrared. Clear skies stay transparent so the map still shows through, while cloud tops brighten with how cold (and tall) they are. Updates every 5 minutes.' },
            { title: 'NHC Hurricanes', desc: 'Full National Hurricane Center overlay: the live storm marker (category icon + name), forecast cone and track, past track, initial wind field, and areas of possible development — tap the storm for its wind, pressure, movement and headline.' },
            { title: 'Spaghetti Models', desc: 'Model track guidance — GFS, UKMET, CMC, NAVGEM, HWRF, HMON, HAFS-A/B, plus the NHC official track and consensus — drawn from NHC a-deck data as its own toggle.' },
            { title: 'Hurricane Hunters', desc: 'Live NOAA and USAF recon aircraft positions, plus the latest reconnaissance flight track with flight-level and surface (SFMR) wind observations.' },
            { title: 'Manual Storm Track Tool', desc: 'Drag on the map in a storm’s direction of motion, enter its speed, and get a projected path (cellular or linear) with estimated arrival times for the communities in its way.' },
            { title: 'More accurate field reports', desc: 'Weather report locations are far more reliable: GPS now refines to its best fix and shows its accuracy, and you can drop and drag a pin to your exact spot — a big help on hotspots and laptops where GPS is coarse.' },
            { title: 'Password help', desc: 'Forgot-password now opens a support ticket, admins can reset any user’s password from the app, and after a reset you’re prompted to choose your own new password at sign-in.' },
            { title: 'Live Cams cleanup', desc: 'Trimmed the camera list to keep feeds streamlined.' },
        ],
    },
];

$('#armrChangelogBtn').click(function () {
    const accent = 'var(--vx-accent)';
    const text = 'rgb(225, 230, 237)';
    const muted = 'rgb(150, 158, 168)';

    const releases = CHANGELOG.map((rel) => {
        const items = rel.items.map((it) => (
            `<div style="margin: 0 0 12px;">
                <div style="font-weight: 700; color: ${text}; font-size: 15px;">${it.title}</div>
                <div style="font-size: 13.5px; color: ${muted}; line-height: 1.5; margin-top: 2px;">${it.desc}</div>
            </div>`
        )).join('');
        return (
            `<div style="margin: 6px 0 14px;">
                <div style="margin: 6px 0 12px; font-size: 13px; text-transform: uppercase; letter-spacing: 0.08em; color: ${accent}; font-weight: 700;">${rel.date}</div>
                ${items}
            </div>`
        );
    }).join('');

    const html_content =
`<div style="text-align: left; padding: 4px 20px; color: ${text};">
<p style="margin: 0 0 6px; color: ${muted};">The latest additions and improvements to Echo Radar.</p>
${releases}
<p style="margin: 14px 0 0; font-size: 12px; color: ${muted};">© 2026 Twistcaster Live Media LLC.</p>
</div>`;

    display_vortex_dialog({
        'title': "What's New",
        'body': html_content,
        'color': 'rgb(230, 230, 230)',
        'textColor': 'black',
    });
});

module.exports = {};
